name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17' # 根据你的 Go 版本调整

      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/your-app-name:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push your-dockerhub-username/your-app-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to server
        run: |
          ssh user@your-server-ip << 'EOF'
            docker pull your-dockerhub-username/your-app-name:latest
            docker stop your-container-name || true
            docker rm your-container-name || true
            docker run -d --name your-container-name -p 80:80 your-dockerhub-username/your-app-name:latest
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
